# Generated by Django 4.1.1 on 2022-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_id', models.CharField(max_length=20)),
                ('app_id', models.CharField(max_length=25)),
                ('app_secret', models.CharField(max_length=40)),
                ('auth_token', models.TextField()),
                ('graph_host_url', models.CharField(default='https://graph.facebook.com', max_length=30)),
                ('api_version', models.CharField(default='v14.0', max_length=5)),
            ],
        ),
    ]
